CREATE TABLE IF NOT EXISTS Comments (
Id TEXT NOT NULL PRIMARY KEY,
Body TEXT NOT NULL ,
CreatorId TEXT,
PostId TEXT,
CreatedAt DATETIME NOT NULL,
Image TEXT,
FOREIGN KEY (CreatorId) REFERENCES Users(Id) ON DELETE CASCADE,
FOREIGN KEY (PostId) REFERENCES Posts(Id) ON DELETE CASCADE
);