CREATE TABLE IF NOT EXISTS Notifications(
   Id TEXT NOT NULL PRIMARY KEY,
   Body TEXT NOT NULL,
   Type TEXT NOT NULL,
   CreatedAt DATETIME NOT NULL,
   ReceiverId TEXT NOT NULL,
   SenderId TEXT NOT NULL,
   Seen TEXT NOT NULL,
   FOREIGN KEY (RecieverId) REFERENCES Users(Id),
   FOREIGN KEY (SenderId) REFERENCES Users(Id)
);