CREATE TABLE IF NOT EXISTS Comments (
Id BLOB NOT NULL PRIMARY KEY,
Body TEXT NOT NULL ,
CreatorId BLOB,
PostId BLOB,
CreatedAt DATETIME NOT NULL,
Image TEXT,
FOREIGN KEY (CreatorId) REFERENCES Users(Id),
FOREIGN KEY (PostId) REFERENCES Posts(Id)
);