name: go tests

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: git_checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: run tests
      run: cd backend && go test -v ./...

    - name: run tests again
      run: cd backend && go test -v ./...